# Generated by Django 5.0.6 on 2024-07-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedad',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
