# Generated by Django 5.0.6 on 2024-07-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_classifiedad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Sold', 'Sold')], default='Active', max_length=10),
        ),
    ]
