# Generated by Django 5.0.6 on 2024-07-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_classifiedad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Sold', 'Sold')], max_length=10),
        ),
    ]
