# Generated by Django 5.0.6 on 2024-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_classifiedad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
