# Generated by Django 5.0.6 on 2024-07-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_logo'),
        ('listing', '0008_alter_classifiedad_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedad',
            name='user',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='list/images/'),
        ),
    ]
